import { EncounterMethod } from '@/lib/static/enums';
import { GameVersion } from '@/lib/static/types';

export const platinum: GameVersion = {
    id: 'platinum',
    label: 'Platinum',
    version: 'platinum',
    region: 'sinnoh',
    generation: 4,
    excludedLocations: [
        'sendoff-spring',
        'newmoon-island',
        'stark-mountain',
        'turnback-cave',
        'snowpoint-temple',
        'maniac-tunnel',
        'sinnoh-route-224',
        'sinnoh-route-225',
        'sinnoh-route-227',
        'sinnoh-route-228',
        'sinnoh-route-229',
        'resort-area',
        'sinnoh-sea-route-226',
        'sinnoh-sea-route-230',
        'spear-pillar',
        'flower-paradise',
        'sinnoh-hall-of-origin-1',
        'sinnoh-hall-of-origin-2',
        'distortion-world',
        'grand-lake',
        'spring-path',
        'sandgem-town',
        'floaroma-town',
        'solaceon-town',
        'jubilife-city',
        'snowpoint-city',
        'pal-park',
        'amity-square',
        'fullmoon-island',
        'galactic-hq',
        'verity-lakefront',
        'sinnoh-battle-tower',
        'fight-area',
        'survival-area',
        'seabreak-path',
        'verity-cavern',
        'valor-cavern',
        'acuity-cavern',
        'jubilife-tv',
        'poketch-co',
        'gts',
        'trainers-school',
        'mining-museum',
        'sinnoh-flower-shop',
        'sinnoh-cycle-shop',
        'contest-hall',
        'poffin-house',
        'sinnoh-foreign-building',
        'pokemon-day-care',
        'veilstone-store',
        'sinnoh-game-corner',
        'canalave-library',
        'vista-lighthouse',
        'sunyshore-market',
        'footstep-house',
        'sinnoh-cafe',
        'sinnoh-restaurant',
        'battle-park',
        'battle-frontier',
        'battle-factory',
        'battle-castle',
        'battle-arcade',
        'battle-hall',
        'sinnoh-global-terminal',
        'sinnoh-villa',
        'battleground',
        'rotoms-room',
        'tg-eterna-bldg',
        'iron-ruins',
        'iceberg-ruins',
        'rock-peak-ruins',
        'roaming-sinnoh',
        'sinnoh-pokemart',
        'mt-coronet-exterior-blizzard',
        'mt-coronet-4f-small-room',
    ],
    excludedSpecies: [
        'mesprit',
        'azelf',
        'uxie',
        'dialga',
        'palkia',
        'giratina',
        'omanyte',
        'kabuto',
        'aerodactyl',
        'lileep',
        'anorith',
    ],
    caveLocations: [
        'iron-island',
        'mt-coronet',
        'oreburgh-gate',
        'oreburgh-mine',
        'ravaged-path',
        'ruin-maniac-cave',
        'sinnoh-victory-road',
        'solaceon-ruins',
        'wayward-cave',
    ],
    methodOverrides: [
        {
            location: 'sinnoh-route-201',
            species: 'turtwig',
            method: EncounterMethod.Starter,
        },
        {
            location: 'sinnoh-route-201',
            species: 'chimchar',
            method: EncounterMethod.Starter,
        },
        {
            location: 'sinnoh-route-201',
            species: 'piplup',
            method: EncounterMethod.Starter,
        },
        {
            location: 'oreburgh-city',
            species: 'cranidos',
            method: EncounterMethod.Fossil,
        },
        {
            location: 'oreburgh-city',
            species: 'shieldon',
            method: EncounterMethod.Fossil,
        },
    ],
    excludedMethods: [
        'super-rod',
        'roaming-grass',
        'roaming-water',
        'pokemon-ranger',
    ],
    excludedConditions: [
        'swarm-yes',
        'radar-on',
        'story-progress-national-dex',
    ],
    excludedConditionPrefixes: ['slot2-'],
    strippedConditions: [
        'slot2-none',
        'radar-none',
        'swarm-no',
        'radar-off',
        'not-mentioned',
    ],
    strippedConditionPrefixes: ['story-progress-', 'item-', 'backlot-'],
    mergedLocations: [
        { from: 'eterna-city-west-gate', into: 'eterna-city-area' },
        ...['b1f', 'b2f', 'b3f', 'b4f'].flatMap((floor) =>
            ['a', 'b', 'c', 'd', 'e']
                .map((suffix) => `solaceon-ruins-${floor}-${suffix}`)
                .map((from) => ({
                    from,
                    into: `solaceon-ruins-${floor}`,
                    mode: 'dedupe' as const,
                }))
        ),
        // The Old Chateau's 2F rooms are disconnected but share the same
        // wild encounters, except old-chateau-2f-left-room, whose table
        // (with time-of-day gastly and the static Rotom encounter) is the
        // authoritative one. Processed in order, so left-room must come
        // last to win.
        ...[
            'private-room',
            'leftmost-room',
            'middle-room',
            'right-room',
            'rightmost-room',
            'left-room',
        ].map((suffix) => ({
            from: `old-chateau-2f-${suffix}`,
            into: 'old-chateau-2f',
            mode: 'replace' as const,
        })),
    ],
    locationSplits: [
        {
            location: 'eterna-forest',
            groups: [
                {
                    key: 'eterna-forest-exterior',
                    methods: [EncounterMethod.HoneyTree],
                },
                {
                    key: 'eterna-forest-interior',
                },
            ],
        },
    ],
};
