interface GameVersion {
    id: string;
    label: string;
    version: string;
    region: string;
    generation: number;
    excludedLocations?: string[];
    excludedSpecies?: string[];
}

export const platinum: GameVersion = {
    id: 'platinum',
    label: 'Platinum',
    version: 'platinum',
    region: 'sinnoh',
    generation: 4,
    excludedLocations: [
        'sendoff-spring',
        'newmoon-island',
        'stark-mountain',
        'turnback-cave',
        'snowpoint-temple',
        'maniac-tunnel',
        'sinnoh-route-224',
        'sinnoh-route-225',
        'sinnoh-route-227',
        'sinnoh-route-228',
        'sinnoh-route-229',
        'resort-area',
        'sinnoh-sea-route-226',
        'sinnoh-sea-route-230',
        'spear-pillar',
        'flower-paradise',
        'sinnoh-hall-of-origin-1',
        'sinnoh-hall-of-origin-2',
        'distortion-world',
        'grand-lake',
        'spring-path',
        'sandgem-town',
        'floaroma-town',
        'solaceon-town',
        'jubilife-city',
        'snowpoint-city',
        'pal-park',
        'amity-square',
        'fullmoon-island',
        'galactic-hq',
        'verity-lakefront',
        'sinnoh-battle-tower',
        'fight-area',
        'survival-area',
        'seabreak-path',
        'verity-cavern',
        'valor-cavern',
        'acuity-cavern',
        'jubilife-tv',
        'poketch-co',
        'gts',
        'trainers-school',
        'mining-museum',
        'sinnoh-flower-shop',
        'sinnoh-cycle-shop',
        'contest-hall',
        'poffin-house',
        'sinnoh-foreign-building',
        'pokemon-day-care',
        'veilstone-store',
        'sinnoh-game-corner',
        'canalave-library',
        'vista-lighthouse',
        'sunyshore-market',
        'footstep-house',
        'sinnoh-cafe',
        'sinnoh-restaurant',
        'battle-park',
        'battle-frontier',
        'battle-factory',
        'battle-castle',
        'battle-arcade',
        'battle-hall',
        'sinnoh-global-terminal',
        'sinnoh-villa',
        'battleground',
        'rotoms-room',
        'tg-eterna-bldg',
        'iron-ruins',
        'iceberg-ruins',
        'rock-peak-ruins',
        'roaming-sinnoh',
        'sinnoh-pokemart',
    ],
    excludedSpecies: [
        'turtwig',
        'chimchar',
        'piplup',
        'mesprit',
        'azelf',
        'uxie',
        'dialga',
        'palkia',
        'giratina',
    ],
};
