import { canalaveCity } from '@/lib/games/platinum/maps';
import { Nature } from '@/lib/static/enums';
import { Location } from '@/lib/static/types';

const CANALAVE_CITY: Location = {
    name: 'Canalave City',
    map: canalaveCity,
    encountersKey: 'canalave-city',
    battles: [
        {
            isMiniboss: true,
            trainerClass: 'PKMN Trainer',
            name: 'Barry 5',
            teamsByStarter: {
                turtwig: [
                    {
                        slug: 'staraptor',
                        ability: 1,
                        gender: 'male',
                        ivs: 12,
                        level: 36,
                        nature: Nature.Bashful,
                        moves: [
                            'aerial-ace',
                            'take-down',
                            'quick-attack',
                            'double-team',
                        ],
                    },
                    {
                        slug: 'floatzel',
                        ability: 1,
                        gender: 'male',
                        ivs: 12,
                        level: 35,
                        nature: Nature.Calm,
                        moves: ['aqua-jet', 'pursuit', 'quick-attack', 'swift'],
                    },
                    {
                        slug: 'heracross',
                        ability: 1,
                        gender: 'male',
                        ivs: 12,
                        level: 37,
                        nature: Nature.Hasty,
                        moves: [
                            'brick-break',
                            'aerial-ace',
                            'night-slash',
                            'horn-attack',
                        ],
                    },
                    {
                        slug: 'roserade',
                        ability: 1,
                        gender: 'male',
                        ivs: 12,
                        level: 35,
                        nature: Nature.Calm,
                        moves: [
                            'giga-drain',
                            'toxic-spikes',
                            'leech-seed',
                            'grass-whistle',
                        ],
                    },
                    {
                        slug: 'infernape',
                        ability: 1,
                        gender: 'male',
                        ivs: 12,
                        level: 38,
                        nature: Nature.Calm,
                        moves: [
                            'brick-break',
                            'flame-wheel',
                            'mach-punch',
                            'aerial-ace',
                        ],
                    },
                ],
                chimchar: [
                    {
                        slug: 'staraptor',
                        ability: 1,
                        gender: 'male',
                        ivs: 12,
                        level: 36,
                        nature: Nature.Serious,
                        moves: [
                            'aerial-ace',
                            'take-down',
                            'quick-attack',
                            'double-team',
                        ],
                    },
                    {
                        slug: 'roserade',
                        ability: 1,
                        gender: 'male',
                        ivs: 12,
                        level: 35,
                        nature: Nature.Naive,
                        moves: [
                            'giga-drain',
                            'toxic-spikes',
                            'leech-seed',
                            'grass-whistle',
                        ],
                    },
                    {
                        slug: 'heracross',
                        ability: 1,
                        gender: 'male',
                        ivs: 12,
                        level: 37,
                        nature: Nature.Bold,
                        moves: [
                            'brick-break',
                            'aerial-ace',
                            'night-slash',
                            'horn-attack',
                        ],
                    },
                    {
                        slug: 'rapidash',
                        ability: 1,
                        gender: 'male',
                        ivs: 12,
                        level: 35,
                        nature: Nature.Timid,
                        moves: ['fire-spin', 'take-down', 'stomp', 'tail-whip'],
                    },
                    {
                        slug: 'empoleon',
                        ability: 1,
                        gender: 'male',
                        ivs: 12,
                        level: 38,
                        nature: Nature.Bashful,
                        moves: [
                            'bubble-beam',
                            'aerial-ace',
                            'metal-claw',
                            'fury-attack',
                        ],
                    },
                ],
                piplup: [
                    {
                        slug: 'staraptor',
                        ability: 1,
                        gender: 'male',
                        ivs: 12,
                        level: 36,
                        nature: Nature.Quirky,
                        moves: [
                            'aerial-ace',
                            'take-down',
                            'quick-attack',
                            'double-team',
                        ],
                    },
                    {
                        slug: 'floatzel',
                        ability: 1,
                        gender: 'male',
                        ivs: 12,
                        level: 35,
                        nature: Nature.Calm,
                        moves: ['aqua-jet', 'pursuit', 'quick-attack', 'swift'],
                    },
                    {
                        slug: 'heracross',
                        ability: 1,
                        gender: 'male',
                        ivs: 12,
                        level: 37,
                        nature: Nature.Hasty,
                        moves: [
                            'brick-break',
                            'aerial-ace',
                            'night-slash',
                            'horn-attack',
                        ],
                    },
                    {
                        slug: 'rapidash',
                        ability: 1,
                        gender: 'male',
                        ivs: 12,
                        level: 35,
                        nature: Nature.Sassy,
                        moves: ['fire-spin', 'take-down', 'stomp', 'tail-whip'],
                    },
                    {
                        slug: 'torterra',
                        ability: 1,
                        gender: 'male',
                        ivs: 12,
                        level: 38,
                        nature: Nature.Mild,
                        moves: [
                            'razor-leaf',
                            'bite',
                            'mega-drain',
                            'leech-seed',
                        ],
                    },
                ],
            },
            x: 48.1,
            y: 29.9,
        },
    ],
};

export default CANALAVE_CITY;
