import { hearthomeGym } from '@/lib/games/platinum/maps';
import { Nature } from '@/lib/static/enums';
import { Location } from '@/lib/static/types';

const HEARTHOME_GYM: Location = {
    name: 'Hearthome Gym',
    map: hearthomeGym,
    battles: [
        {
            isOptional: true,
            trainerClass: 'Lass',
            name: 'Molly',
            team: [
                {
                    slug: 'misdreavus',
                    ability: 1,
                    gender: 'female',
                    level: 23,
                    nature: Nature.Hardy,
                    moves: ['pain-split', 'psybeam', 'confuse-ray'],
                    ivs: 1,
                },
            ],
            x: 35.7,
            y: 74,
        },
        {
            isOptional: true,
            trainerClass: 'Youngster',
            name: 'Donny',
            team: [
                {
                    slug: 'gastly',
                    ability: 1,
                    gender: 'male',
                    level: 20,
                    nature: Nature.Careful,
                    moves: [
                        'sucker-punch',
                        'night-shade',
                        'confuse-ray',
                        'curse',
                    ],
                    ivs: 1,
                },
                {
                    slug: 'drifloon',
                    ability: 1,
                    gender: 'male',
                    level: 22,
                    nature: Nature.Docile,
                    moves: ['spit-up', 'swallow', 'stockpile'],
                    ivs: 1,
                },
            ],
            x: 60.7,
            y: 74,
        },
        {
            isOptional: true,
            trainerClass: 'School Kid F',
            name: 'Mackenzie',
            team: [
                {
                    slug: 'drifloon',
                    ability: 1,
                    gender: 'female',
                    level: 21,
                    nature: Nature.Quiet,
                    moves: ['payback', 'gust', 'astonish', 'minimize'],
                    ivs: 1,
                },
                {
                    slug: 'drifloon',
                    ability: 1,
                    gender: 'female',
                    level: 21,
                    nature: Nature.Quiet,
                    moves: ['spit-up', 'swallow', 'stockpile'],
                    ivs: 1,
                },
            ],
            x: 21.4,
            y: 49.9,
            items: [{ count: 1, name: 'Super Potion' }],
        },
        {
            isOptional: true,
            trainerClass: 'School Kid M',
            name: 'Chance',
            team: [
                {
                    slug: 'gastly',
                    ability: 1,
                    gender: 'male',
                    level: 23,
                    nature: Nature.Rash,
                    moves: [
                        'night-shade',
                        'sucker-punch',
                        'confuse-ray',
                        'hypnosis',
                    ],
                    ivs: 1,
                },
            ],
            x: 74.9,
            y: 50.3,
            items: [{ count: 1, name: 'X Defend' }],
        },
        {
            isOptional: true,
            trainerClass: 'Ace Trainer F',
            name: 'Catherine',
            team: [
                {
                    slug: 'haunter',
                    ability: 1,
                    gender: 'female',
                    level: 23,
                    nature: Nature.Bashful,
                    moves: [
                        'night-shade',
                        'confuse-ray',
                        'sucker-punch',
                        'curse',
                    ],
                    ivs: 7,
                },
                {
                    slug: 'misdreavus',
                    ability: 1,
                    gender: 'female',
                    level: 24,
                    nature: Nature.Careful,
                    moves: ['psybeam', 'pain-split', 'confuse-ray', 'spite'],
                    ivs: 7,
                },
            ],
            x: 39.2,
            y: 35.5,
        },
        {
            isOptional: true,
            trainerClass: 'Ace Trainer M',
            name: 'Allen',
            team: [
                {
                    slug: 'gastly',
                    ability: 1,
                    gender: 'male',
                    level: 21,
                    nature: Nature.Quirky,
                    moves: [
                        'night-shade',
                        'sucker-punch',
                        'curse',
                        'confuse-ray',
                    ],
                    ivs: 7,
                },
                {
                    slug: 'gastly',
                    ability: 1,
                    gender: 'male',
                    level: 22,
                    nature: Nature.Calm,
                    moves: [
                        'night-shade',
                        'sucker-punch',
                        'hypnosis',
                        'confuse-ray',
                    ],
                    ivs: 7,
                },
                {
                    slug: 'haunter',
                    ability: 1,
                    gender: 'male',
                    level: 24,
                    nature: Nature.Serious,
                    moves: ['shadow-ball', 'confuse-ray', 'curse', 'mean-look'],
                    ivs: 7,
                },
            ],
            x: 67.7,
            y: 37.2,
        },
        {
            isBoss: true,
            trainerClass: 'Leader',
            name: 'Fantina',
            team: [
                {
                    slug: 'duskull',
                    ability: 1,
                    gender: 'female',
                    level: 24,
                    nature: Nature.Mild,
                    moves: [
                        'will-o-wisp',
                        'pursuit',
                        'shadow-sneak',
                        'future-sight',
                    ],
                    ivs: 12,
                },
                {
                    slug: 'haunter',
                    ability: 1,
                    gender: 'female',
                    level: 24,
                    nature: Nature.Bashful,
                    moves: [
                        'shadow-claw',
                        'sucker-punch',
                        'hypnosis',
                        'confuse-ray',
                    ],
                    ivs: 12,
                },
                {
                    slug: 'mismagius',
                    ability: 1,
                    gender: 'female',
                    level: 26,
                    nature: Nature.Impish,
                    moves: [
                        'shadow-ball',
                        'psybeam',
                        'magical-leaf',
                        'confuse-ray',
                    ],
                    ivs: 12,
                    heldItem: 'sitrus-berry',
                },
            ],
            x: 49.9,
            y: 17.4,
            items: [{ count: 2, name: 'Super Potion' }],
        },
    ],
};

export default HEARTHOME_GYM;
