import {
    ironIsland1f,
    ironIslandB1fEast,
    ironIslandB1fWest,
    ironIslandB2fEast,
    ironIslandB2fWest,
    ironIslandB3f,
    ironIslandExterior,
} from '@/lib/games/platinum/maps';
import { Nature } from '@/lib/static/enums';
import { Location } from '@/lib/static/types';

const IRON_ISLAND: Location = {
    name: 'Iron Island',
    subareas: [
        {
            name: 'Exterior',
            map: ironIslandExterior,
            encountersKey: 'iron-island-area',
        },
        {
            name: '1F',
            map: ironIsland1f,
            encountersKey: 'iron-island-1f',
        },
        {
            name: 'B1F West',
            map: ironIslandB1fWest,
            encountersKey: 'iron-island-b1f-left',
            battles: [
                {
                    isOptional: true,
                    trainerClass: 'Camper',
                    name: 'Lawrence',
                    team: [
                        {
                            slug: 'aipom',
                            ability: 1,
                            gender: 'male',
                            level: 34,
                            nature: Nature.Naive,
                        },
                        {
                            slug: 'floatzel',
                            ability: 1,
                            gender: 'male',
                            level: 36,
                            nature: Nature.Jolly,
                        },
                    ],
                    x: 64.2,
                    y: 81.1,
                },
            ],
        },
        {
            name: 'B1F East',
            map: ironIslandB1fEast,
            encountersKey: 'iron-island-b1f-right',
            battles: [
                {
                    isOptional: true,
                    trainerClass: 'Picnicker',
                    name: 'Summer',
                    team: [
                        {
                            slug: 'raichu',
                            ability: 1,
                            gender: 'female',
                            level: 37,
                            nature: Nature.Mild,
                        },
                    ],
                    x: 76.1,
                    y: 48.6,
                },
            ],
        },
        {
            name: 'B2F East',
            map: ironIslandB2fEast,
            encountersKey: 'iron-island-b2f-right',
            battles: [
                {
                    isOptional: true,
                    trainerClass: 'Worker',
                    name: 'Noel',
                    team: [
                        {
                            slug: 'magnemite',
                            ability: 1,
                            gender: 'male',
                            level: 34,
                            nature: Nature.Timid,
                        },
                        {
                            slug: 'magnemite',
                            ability: 1,
                            gender: 'male',
                            level: 36,
                            nature: Nature.Lax,
                        },
                    ],
                    x: 39.5,
                    y: 27.3,
                },
                {
                    isOptional: true,
                    trainerClass: 'Worker',
                    name: 'Braden',
                    team: [
                        {
                            slug: 'steelix',
                            ability: 1,
                            gender: 'male',
                            level: 37,
                            nature: Nature.Calm,
                        },
                    ],
                    x: 20.3,
                    y: 56.8,
                },
            ],
        },
        {
            name: 'B2F West',
            map: ironIslandB2fWest,
            encountersKey: 'iron-island-b2f-left',
            battles: [
                {
                    isOptional: true,
                    trainerClass: 'Hiker',
                    name: 'Damon',
                    team: [
                        {
                            slug: 'nosepass',
                            ability: 1,
                            gender: 'male',
                            level: 35,
                            nature: Nature.Bold,
                        },
                        {
                            slug: 'onix',
                            ability: 1,
                            gender: 'male',
                            level: 33,
                            nature: Nature.Lonely,
                        },
                        {
                            slug: 'steelix',
                            ability: 1,
                            gender: 'male',
                            level: 34,
                            nature: Nature.Mild,
                        },
                    ],
                    x: 64.7,
                    y: 5.7,
                },
                {
                    isOptional: true,
                    trainerClass: 'Hiker',
                    name: 'Maurice',
                    team: [
                        {
                            slug: 'graveler',
                            ability: 1,
                            gender: 'male',
                            level: 35,
                            nature: Nature.Docile,
                        },
                        {
                            slug: 'rhyhorn',
                            ability: 1,
                            gender: 'male',
                            level: 35,
                            nature: Nature.Lonely,
                        },
                    ],
                    x: 52.5,
                    y: 9,
                },
                {
                    isOptional: true,
                    trainerClass: 'Black Belt',
                    name: 'Kendal',
                    team: [
                        {
                            slug: 'toxicroak',
                            ability: 1,
                            gender: 'male',
                            ivs: 3,
                            level: 38,
                            nature: Nature.Mild,
                        },
                    ],
                    x: 89,
                    y: 33.1,
                },
                {
                    isOptional: true,
                    trainerClass: 'Battle Girl',
                    name: 'Tyler',
                    team: [
                        {
                            slug: 'medicham',
                            ability: 1,
                            gender: 'female',
                            ivs: 3,
                            level: 38,
                            nature: Nature.Sassy,
                        },
                    ],
                    x: 89,
                    y: 38.1,
                },
                {
                    isOptional: true,
                    trainerClass: 'Worker',
                    name: 'Brendon',
                    team: [
                        {
                            slug: 'geodude',
                            ability: 1,
                            gender: 'male',
                            level: 33,
                            nature: Nature.Relaxed,
                        },
                        {
                            slug: 'geodude',
                            ability: 1,
                            gender: 'male',
                            level: 33,
                            nature: Nature.Relaxed,
                        },
                        {
                            slug: 'machoke',
                            ability: 1,
                            gender: 'male',
                            level: 36,
                            nature: Nature.Adamant,
                        },
                    ],
                    x: 37.9,
                    y: 45,
                },
                {
                    isOptional: true,
                    trainerClass: 'Worker',
                    name: 'Quentin',
                    team: [
                        {
                            slug: 'magnemite',
                            ability: 1,
                            gender: 'male',
                            level: 34,
                            nature: Nature.Jolly,
                        },
                        {
                            slug: 'machop',
                            ability: 1,
                            gender: 'male',
                            level: 34,
                            nature: Nature.Jolly,
                        },
                        {
                            slug: 'graveler',
                            ability: 1,
                            gender: 'male',
                            level: 34,
                            nature: Nature.Timid,
                        },
                    ],
                    x: 35.4,
                    y: 50.1,
                },
                {
                    isOptional: true,
                    trainerClass: 'Ace Trainer M',
                    name: 'Jonah',
                    team: [
                        {
                            slug: 'quagsire',
                            ability: 1,
                            gender: 'male',
                            ivs: 6,
                            level: 35,
                            nature: Nature.Gentle,
                        },
                        {
                            slug: 'staraptor',
                            ability: 1,
                            gender: 'male',
                            ivs: 6,
                            level: 36,
                            nature: Nature.Mild,
                        },
                        {
                            slug: 'hippopotas',
                            ability: 1,
                            gender: 'male',
                            ivs: 6,
                            level: 38,
                            nature: Nature.Rash,
                        },
                    ],
                    x: 57.4,
                    y: 53.6,
                },
                {
                    isOptional: true,
                    trainerClass: 'Ace Trainer F',
                    name: 'Brenda',
                    team: [
                        {
                            slug: 'lopunny',
                            ability: 1,
                            gender: 'female',
                            ivs: 6,
                            level: 38,
                            nature: Nature.Quirky,
                        },
                        {
                            slug: 'kirlia',
                            ability: 1,
                            gender: 'female',
                            ivs: 6,
                            level: 36,
                            nature: Nature.Naive,
                        },
                        {
                            slug: 'medicham',
                            ability: 1,
                            gender: 'female',
                            ivs: 6,
                            level: 35,
                            nature: Nature.Rash,
                        },
                    ],
                    x: 67.3,
                    y: 53.6,
                },
                {
                    isOptional: true,
                    isTag: true,
                    customHeight: 38,
                    trainerClass: 'Galactic Grunt M and Galactic Grunt M',
                    name: '3',
                    team: [
                        {
                            slug: 'zubat',
                            ability: 1,
                            gender: 'male',
                            ivs: 3,
                            level: 34,
                            nature: Nature.Careful,
                        },
                        {
                            slug: 'houndour',
                            ability: 1,
                            gender: 'male',
                            ivs: 3,
                            level: 34,
                            nature: Nature.Jolly,
                        },
                        {
                            slug: 'golbat',
                            ability: 1,
                            gender: 'male',
                            ivs: 3,
                            level: 34,
                            nature: Nature.Careful,
                        },
                        {
                            slug: 'glameow',
                            ability: 1,
                            gender: 'male',
                            ivs: 3,
                            level: 34,
                            nature: Nature.Mild,
                        },
                        {
                            slug: 'stunky',
                            ability: 1,
                            gender: 'male',
                            ivs: 3,
                            level: 34,
                            nature: Nature.Jolly,
                        },
                        {
                            slug: 'croagunk',
                            ability: 1,
                            gender: 'male',
                            ivs: 3,
                            level: 34,
                            nature: Nature.Quiet,
                        },
                    ],
                    x: 47.8,
                    y: 69.8,
                },
            ],
        },
        {
            name: 'B3F',
            map: ironIslandB3f,
            encountersKey: 'iron-island-b3f',
        },
    ],
};

export default IRON_ISLAND;
