import { pastoriaGym } from '@/lib/games/platinum/maps';
import { Nature } from '@/lib/static/enums';
import { Location } from '@/lib/static/types';

const PASTORIA_GYM: Location = {
    name: 'Pastoria Gym',
    map: pastoriaGym,
    battles: [
        {
            trainerClass: 'Tuber M',
            name: 'Jacky',
            team: [
                {
                    slug: 'bibarel',
                    ability: 1,
                    gender: 'male',
                    ivs: 1,
                    level: 32,
                    nature: Nature.Hasty,
                    moves: ['water-gun', 'rollout', 'hyper-fang', 'yawn'],
                },
            ],
            x: 42.4,
            y: 75.7,
        },
        {
            isOptional: true,
            trainerClass: 'Fisherman',
            name: 'Walter',
            team: [
                {
                    slug: 'whiscash',
                    ability: 1,
                    gender: 'male',
                    ivs: 1,
                    level: 33,
                    nature: Nature.Brave,
                    moves: ['water-pulse', 'magnitude'],
                },
            ],
            x: 34.5,
            y: 25.5,
        },
        {
            trainerClass: 'Sailor',
            name: 'Damian',
            team: [
                {
                    slug: 'wingull',
                    ability: 1,
                    gender: 'male',
                    ivs: 1,
                    level: 31,
                    nature: Nature.Bashful,
                    moves: ['water-pulse', 'wing-attack', 'quick-attack'],
                },
                {
                    slug: 'pelipper',
                    ability: 1,
                    gender: 'male',
                    ivs: 1,
                    level: 31,
                    nature: Nature.Naive,
                    moves: ['water-pulse', 'wing-attack', 'quick-attack'],
                },
            ],
            x: 26.8,
            y: 50.1,
        },
        {
            trainerClass: 'Tuber F',
            name: 'Caitlyn',
            team: [
                {
                    slug: 'azurill',
                    ability: 1,
                    gender: 'female',
                    ivs: 1,
                    level: 27,
                    nature: Nature.Jolly,
                    moves: ['water-gun', 'slam', 'charm'],
                },
                {
                    slug: 'marill',
                    ability: 1,
                    gender: 'female',
                    ivs: 1,
                    level: 29,
                    nature: Nature.Naughty,
                    moves: [
                        'bubble-beam',
                        'rollout',
                        'defense-curl',
                        'aqua-ring',
                    ],
                },
                {
                    slug: 'azumarill',
                    ability: 1,
                    gender: 'female',
                    ivs: 1,
                    level: 31,
                    nature: Nature.Careful,
                    moves: [
                        'bubble-beam',
                        'double-edge',
                        'rollout',
                        'aqua-ring',
                    ],
                },
            ],
            x: 80.9,
            y: 75.7,
        },
        {
            isOptional: true,
            trainerClass: 'Fisherman',
            name: 'Erick',
            team: [
                {
                    slug: 'goldeen',
                    ability: 1,
                    gender: 'male',
                    ivs: 1,
                    level: 28,
                    nature: Nature.Impish,
                    moves: ['water-pulse', 'peck', 'flail', 'supersonic'],
                },
                {
                    slug: 'seaking',
                    ability: 1,
                    gender: 'male',
                    ivs: 1,
                    level: 31,
                    nature: Nature.Hasty,
                    moves: [
                        'water-pulse',
                        'fury-attack',
                        'flail',
                        'supersonic',
                    ],
                },
                {
                    slug: 'gyarados',
                    ability: 1,
                    gender: 'male',
                    ivs: 1,
                    level: 31,
                    nature: Nature.Bashful,
                    moves: ['thrash', 'bite'],
                },
            ],
            x: 73.2,
            y: 41.3,
        },
        {
            trainerClass: 'Sailor',
            name: 'Samson',
            team: [
                {
                    slug: 'wingull',
                    ability: 1,
                    gender: 'male',
                    ivs: 1,
                    level: 29,
                    nature: Nature.Brave,
                    moves: ['water-pulse', 'wing-attack', 'supersonic'],
                },
                {
                    slug: 'shellos',
                    ability: 1,
                    gender: 'male',
                    ivs: 1,
                    level: 30,
                    nature: Nature.Brave,
                    moves: ['water-pulse', 'mud-bomb', 'rain-dance'],
                },
                {
                    slug: 'golduck',
                    ability: 1,
                    gender: 'male',
                    ivs: 1,
                    level: 31,
                    nature: Nature.Lax,
                    moves: ['fury-swipes', 'confusion', 'water-pulse'],
                },
            ],
            x: 19.1,
            y: 18.8,
        },
        {
            isBoss: true,
            trainerClass: 'Leader',
            name: 'Wake',
            team: [
                {
                    slug: 'gyarados',
                    ability: 1,
                    gender: 'male',
                    ivs: 18,
                    level: 33,
                    nature: Nature.Lax,
                    moves: ['waterfall', 'brine', 'bite', 'twister'],
                },
                {
                    slug: 'quagsire',
                    ability: 1,
                    gender: 'male',
                    ivs: 18,
                    level: 34,
                    nature: Nature.Naughty,
                    moves: ['mud-shot', 'rock-tomb', 'water-pulse', 'yawn'],
                },
                {
                    slug: 'floatzel',
                    ability: 1,
                    gender: 'male',
                    ivs: 18,
                    level: 37,
                    nature: Nature.Naughty,
                    moves: ['brine', 'ice-fang', 'crunch', 'aqua-jet'],
                    heldItem: 'sitrus-berry',
                },
            ],
            items: [{ count: 2, name: 'Hyper Potion' }],
            x: 49.9,
            y: 9.7,
        },
    ],
};

export default PASTORIA_GYM;
