import { route215 } from '@/lib/games/platinum/maps';
import { FieldCondition, Nature } from '@/lib/static/enums';
import { Location } from '@/lib/static/types';

const ROUTE_215: Location = {
    name: 'Route 215',
    map: route215,
    encountersKey: 'sinnoh-route-215',
    battles: [
        {
            trainerClass: 'Ruin Maniac',
            name: 'Calvin',
            team: [
                {
                    slug: 'bronzor',
                    ability: 1,
                    gender: 'male',
                    level: 23,
                    nature: Nature.Sassy,
                },
                {
                    slug: 'shieldon',
                    ability: 1,
                    gender: 'male',
                    level: 23,
                    nature: Nature.Careful,
                },
            ],
            x: 14.1,
            y: 56,
            fieldCondition: FieldCondition.Rain,
        },
        {
            isOptional: true,
            trainerClass: 'Jogger',
            name: 'Craig',
            team: [
                {
                    slug: 'luxio',
                    ability: 1,
                    gender: 'male',
                    level: 22,
                    nature: Nature.Naughty,
                },
                {
                    slug: 'luxio',
                    ability: 1,
                    gender: 'male',
                    level: 24,
                    nature: Nature.Careful,
                },
            ],
            x: 23.5,
            y: 59,
            fieldCondition: FieldCondition.Rain,
        },
        {
            isOptional: true,
            trainerClass: 'Black Belt',
            name: 'Derek',
            team: [
                {
                    slug: 'croagunk',
                    ability: 1,
                    gender: 'male',
                    level: 26,
                    nature: Nature.Bashful,
                    ivs: 3,
                },
            ],
            x: 32.9,
            y: 37.2,
            fieldCondition: FieldCondition.Rain,
        },
        {
            isOptional: true,
            trainerClass: 'Black Belt',
            name: 'Gregory',
            team: [
                {
                    slug: 'machop',
                    ability: 1,
                    gender: 'male',
                    level: 23,
                    nature: Nature.Adamant,
                    ivs: 3,
                },
                {
                    slug: 'machop',
                    ability: 1,
                    gender: 'male',
                    level: 23,
                    nature: Nature.Adamant,
                    ivs: 3,
                },
                {
                    slug: 'machop',
                    ability: 1,
                    gender: 'male',
                    level: 23,
                    nature: Nature.Adamant,
                    ivs: 3,
                },
            ],
            x: 47.5,
            y: 18,
            fieldCondition: FieldCondition.Rain,
        },
        {
            isOptional: true,
            trainerClass: 'Black Belt',
            name: 'Nathaniel',
            team: [
                {
                    slug: 'croagunk',
                    ability: 1,
                    gender: 'male',
                    level: 21,
                    nature: Nature.Naive,
                    ivs: 3,
                },
                {
                    slug: 'meditite',
                    ability: 1,
                    gender: 'male',
                    level: 24,
                    nature: Nature.Relaxed,
                    ivs: 3,
                },
                {
                    slug: 'machop',
                    ability: 1,
                    gender: 'male',
                    level: 24,
                    nature: Nature.Sassy,
                    ivs: 3,
                },
            ],
            x: 70.5,
            y: 30,
            fieldCondition: FieldCondition.Rain,
        },
        {
            isOptional: true,
            trainerClass: 'Jogger',
            name: 'Scott',
            team: [
                {
                    slug: 'staravia',
                    ability: 1,
                    gender: 'male',
                    level: 25,
                    nature: Nature.Jolly,
                },
            ],
            x: 80.9,
            y: 65,
            fieldCondition: FieldCondition.Rain,
        },
        {
            trainerClass: 'Ace Trainer F',
            name: 'Maya',
            team: [
                {
                    slug: 'roselia',
                    ability: 1,
                    gender: 'female',
                    level: 24,
                    moves: ['toxic-spikes', 'giga-drain', 'leech-seed'],
                    nature: Nature.Adamant,
                    ivs: 6,
                },
                {
                    slug: 'ralts',
                    ability: 1,
                    gender: 'female',
                    level: 24,
                    moves: [
                        'psychic',
                        'magical-leaf',
                        'calm-mind',
                        'double-team',
                    ],
                    nature: Nature.Serious,
                    ivs: 6,
                },
                {
                    slug: 'lickitung',
                    ability: 1,
                    gender: 'female',
                    level: 25,
                    moves: ['supersonic', 'stomp', 'rollout', 'defense-curl'],
                    nature: Nature.Modest,
                    ivs: 6,
                },
            ],
            x: 75.5,
            y: 75.7,
            fieldCondition: FieldCondition.Rain,
        },
        {
            trainerClass: 'Ace Trainer M',
            name: 'Dennis',
            team: [
                {
                    slug: 'gligar',
                    ability: 1,
                    gender: 'male',
                    level: 24,
                    moves: [
                        'screech',
                        'feint-attack',
                        'quick-attack',
                        'poison-sting',
                    ],
                    nature: Nature.Bold,
                    ivs: 6,
                },
                {
                    slug: 'buizel',
                    ability: 1,
                    gender: 'male',
                    level: 24,
                    moves: ['aqua-jet', 'swift', 'pursuit', 'quick-attack'],
                    nature: Nature.Naive,
                    ivs: 6,
                },
                {
                    slug: 'drifblim',
                    ability: 1,
                    gender: 'male',
                    level: 25,
                    moves: ['swallow', 'gust', 'stockpile', 'ominous-wind'],
                    nature: Nature.Bold,
                    ivs: 6,
                },
            ],
            x: 75.5,
            y: 85.2,
            fieldCondition: FieldCondition.Rain,
        },
    ],
};

export default ROUTE_215;
