import { route210North, route210South } from '@/lib/games/platinum/maps';
import { FieldCondition, Nature } from '@/lib/static/enums';
import { Location } from '@/lib/static/types';

const ROUTE_210: Location = {
    name: 'Route 210',
    subareas: [
        {
            name: 'South',
            map: route210South,
            encountersKey: 'sinnoh-route-210-south-towards-solaceon-town',
            battles: [
                {
                    isOptional: true,
                    trainerClass: 'Rancher',
                    name: 'Marco',
                    team: [
                        {
                            slug: 'ponyta',
                            ability: 1,
                            gender: 'male',
                            level: 24,
                            nature: Nature.Docile,
                        },
                    ],
                    x: 34.6,
                    y: 77,
                },
                {
                    isOptional: true,
                    trainerClass: 'Jogger',
                    name: 'Wyatt',
                    team: [
                        {
                            slug: 'pikachu',
                            ability: 1,
                            gender: 'male',
                            level: 24,
                            nature: Nature.Sassy,
                        },
                    ],
                    x: 71.4,
                    y: 69,
                },
                {
                    isOptional: true,
                    isTrueDouble: true,
                    isDoubleHeightMarker: true,
                    trainerClass: 'Belle & Pa',
                    name: 'Ava & Matt',
                    team: [
                        {
                            slug: 'ponyta',
                            ability: 1,
                            gender: 'male',
                            level: 24,
                            nature: Nature.Naughty,
                        },
                        {
                            slug: 'rapidash',
                            ability: 1,
                            gender: 'male',
                            level: 24,
                            nature: Nature.Calm,
                        },
                    ],
                    x: 60.3,
                    y: 56.4,
                },
                {
                    isOptional: true,
                    isTrueDouble: true,
                    isDoubleWidthMarker: true,
                    trainerClass: 'Twins',
                    name: 'Teri & Tia',
                    team: [
                        {
                            slug: 'pikachu',
                            ability: 1,
                            gender: 'female',
                            level: 23,
                            nature: Nature.Adamant,
                        },
                        {
                            slug: 'clefairy',
                            ability: 1,
                            gender: 'female',
                            level: 23,
                            nature: Nature.Adamant,
                        },
                    ],
                    x: 42.5,
                    y: 45.5,
                },
                {
                    isOptional: true,
                    trainerClass: 'Pkmn Breeder M',
                    name: 'Kahlil',
                    team: [
                        {
                            slug: 'elekid',
                            ability: 1,
                            gender: 'male',
                            level: 23,
                            nature: Nature.Gentle,
                        },
                        {
                            slug: 'happiny',
                            ability: 1,
                            gender: 'female',
                            level: 23,
                            nature: Nature.Bold,
                        },
                    ],
                    x: 31.7,
                    y: 36.2,
                },
                {
                    isOptional: true,
                    trainerClass: 'Pkmn Breeder F',
                    name: 'Amber',
                    team: [
                        {
                            slug: 'magby',
                            ability: 1,
                            gender: 'female',
                            level: 23,
                            nature: Nature.Brave,
                        },
                        {
                            slug: 'togepi',
                            ability: 1,
                            gender: 'female',
                            level: 23,
                            nature: Nature.Modest,
                        },
                    ],
                    x: 60,
                    y: 30.8,
                },
            ],
        },
        {
            name: 'North',
            map: route210North,
            encountersKey: 'sinnoh-route-210-west-towards-celestic-town',
            battles: [
                {
                    isOptional: true,
                    trainerClass: 'Ninja Boy',
                    name: 'Brennan',
                    team: [
                        {
                            slug: 'zubat',
                            ability: 1,
                            gender: 'male',
                            level: 30,
                            nature: Nature.Impish,
                        },
                        {
                            slug: 'skorupi',
                            ability: 1,
                            gender: 'male',
                            level: 32,
                            nature: Nature.Naive,
                        },
                    ],
                    x: 73.6,
                    y: 81.7,
                },
                {
                    isOptional: true,
                    trainerClass: 'Ninja Boy',
                    name: 'Fabian',
                    team: [
                        {
                            slug: 'croagunk',
                            ability: 1,
                            gender: 'male',
                            level: 31,
                            nature: Nature.Naive,
                        },
                        {
                            slug: 'croagunk',
                            ability: 1,
                            gender: 'male',
                            level: 31,
                            nature: Nature.Naive,
                        },
                    ],
                    x: 86.3,
                    y: 80.6,
                },
                {
                    isOptional: true,
                    trainerClass: 'Ninja Boy',
                    name: 'Bruce',
                    team: [
                        {
                            slug: 'stunky',
                            ability: 1,
                            gender: 'male',
                            level: 33,
                            nature: Nature.Modest,
                        },
                    ],
                    x: 96.7,
                    y: 70,
                },
                {
                    isOptional: true,
                    trainerClass: 'Ninja Boy',
                    name: 'Joel',
                    team: [
                        {
                            slug: 'zubat',
                            ability: 1,
                            gender: 'male',
                            level: 29,
                            nature: Nature.Adamant,
                        },
                        {
                            slug: 'skorupi',
                            ability: 1,
                            gender: 'male',
                            level: 29,
                            nature: Nature.Hardy,
                        },
                        {
                            slug: 'stunky',
                            ability: 1,
                            gender: 'male',
                            level: 29,
                            nature: Nature.Lonely,
                        },
                        {
                            slug: 'golbat',
                            ability: 1,
                            gender: 'male',
                            level: 29,
                            nature: Nature.Calm,
                        },
                    ],
                    fieldCondition: FieldCondition.Fog,
                    x: 88.2,
                    y: 29,
                },
                {
                    trainerClass: 'Ace Trainer F',
                    name: 'Alyssa',
                    team: [
                        {
                            slug: 'aipom',
                            ability: 1,
                            gender: 'female',
                            ivs: 6,
                            level: 32,
                            nature: Nature.Bashful,
                            moves: [
                                'swift',
                                'water-pulse',
                                'shock-wave',
                                'aerial-ace',
                            ],
                        },
                        {
                            slug: 'girafarig',
                            ability: 1,
                            gender: 'female',
                            ivs: 6,
                            level: 32,
                            nature: Nature.Rash,
                            moves: [
                                'double-hit',
                                'psybeam',
                                'assurance',
                                'light-screen',
                            ],
                        },
                        {
                            slug: 'grotle',
                            ability: 1,
                            gender: 'female',
                            ivs: 6,
                            level: 33,
                            nature: Nature.Timid,
                            moves: ['mega-drain', 'bite', 'curse'],
                        },
                    ],
                    fieldCondition: FieldCondition.Fog,
                    x: 70.4,
                    y: 32.6,
                },
                {
                    isOptional: true,
                    isTrueDouble: true,
                    isDoubleWidthMarker: true,
                    trainerClass: 'Double Team',
                    name: 'Zac & Jen',
                    team: [
                        {
                            slug: 'gyarados',
                            ability: 1,
                            gender: 'male',
                            ivs: 6,
                            level: 36,
                            nature: Nature.Naive,
                        },
                        {
                            slug: 'raichu',
                            ability: 1,
                            gender: 'male',
                            ivs: 6,
                            level: 36,
                            nature: Nature.Careful,
                        },
                    ],
                    fieldCondition: FieldCondition.Fog,
                    x: 61.6,
                    y: 22.6,
                },
                {
                    isOptional: true,
                    trainerClass: 'Ace Trainer M',
                    name: 'Ernest',
                    team: [
                        {
                            slug: 'scyther',
                            ability: 1,
                            gender: 'male',
                            ivs: 6,
                            level: 32,
                            nature: Nature.Bashful,
                            moves: [
                                'slash',
                                'wing-attack',
                                'pursuit',
                                'quick-attack',
                            ],
                        },
                        {
                            slug: 'probopass',
                            ability: 1,
                            gender: 'male',
                            ivs: 6,
                            level: 31,
                            nature: Nature.Jolly,
                            moves: [
                                'thunder-wave',
                                'rock-slide',
                                'magnet-bomb',
                                'iron-defense',
                            ],
                        },
                        {
                            slug: 'luxio',
                            ability: 1,
                            gender: 'male',
                            ivs: 6,
                            level: 34,
                            nature: Nature.Brave,
                            moves: [
                                'thunderbolt',
                                'crunch',
                                'swagger',
                                'double-team',
                            ],
                        },
                    ],
                    fieldCondition: FieldCondition.Fog,
                    x: 56.8,
                    y: 10.2,
                },
                {
                    isOptional: true,
                    trainerClass: 'Ninja Boy',
                    name: 'Davido',
                    team: [
                        {
                            slug: 'mothim',
                            ability: 1,
                            gender: 'male',
                            level: 33,
                            nature: Nature.Rash,
                        },
                    ],
                    fieldCondition: FieldCondition.Fog,
                    x: 20.1,
                    y: 9.2,
                },
                {
                    trainerClass: 'Black Belt',
                    name: 'Adam',
                    team: [
                        {
                            slug: 'machoke',
                            ability: 1,
                            gender: 'male',
                            ivs: 3,
                            level: 34,
                            nature: Nature.Hasty,
                        },
                    ],
                    fieldCondition: FieldCondition.Fog,
                    x: 40.1,
                    y: 34.2,
                },
                {
                    isOptional: true,
                    trainerClass: 'Ninja Boy',
                    name: 'Nathan',
                    team: [
                        {
                            slug: 'stunky',
                            ability: 1,
                            gender: 'male',
                            level: 31,
                            nature: Nature.Bashful,
                        },
                        {
                            slug: 'golbat',
                            ability: 1,
                            gender: 'male',
                            level: 31,
                            nature: Nature.Bashful,
                        },
                    ],
                    fieldCondition: FieldCondition.Fog,
                    x: 47.5,
                    y: 30.7,
                },
                {
                    trainerClass: 'Bird Keeper',
                    name: 'Brianna',
                    team: [
                        {
                            slug: 'hoothoot',
                            ability: 1,
                            gender: 'male',
                            ivs: 6,
                            level: 31,
                            nature: Nature.Bashful,
                        },
                        {
                            slug: 'noctowl',
                            ability: 1,
                            gender: 'male',
                            ivs: 6,
                            level: 33,
                            nature: Nature.Gentle,
                        },
                    ],
                    fieldCondition: FieldCondition.Fog,
                    x: 32.8,
                    y: 29.3,
                },
                {
                    isOptional: true,
                    trainerClass: 'Veteran',
                    name: 'Brian',
                    team: [
                        {
                            slug: 'tangela',
                            ability: 1,
                            gender: 'male',
                            ivs: 12,
                            level: 32,
                            nature: Nature.Adamant,
                            moves: [
                                'ingrain',
                                'giga-drain',
                                'ancient-power',
                                'toxic',
                            ],
                        },
                        {
                            slug: 'ponyta',
                            ability: 1,
                            gender: 'male',
                            ivs: 12,
                            level: 32,
                            nature: Nature.Quiet,
                            moves: ['fire-spin', 'stomp', 'take-down'],
                        },
                        {
                            slug: 'buizel',
                            ability: 1,
                            gender: 'male',
                            ivs: 12,
                            level: 32,
                            nature: Nature.Brave,
                            moves: [
                                'aqua-jet',
                                'whirlpool',
                                'pursuit',
                                'quick-attack',
                            ],
                        },
                    ],
                    fieldCondition: FieldCondition.Fog,
                    x: 15.1,
                    y: 22.8,
                },
                {
                    isOptional: true,
                    trainerClass: 'Dragon Tamer',
                    name: 'Patrick',
                    team: [
                        {
                            slug: 'gible',
                            ability: 1,
                            gender: 'male',
                            ivs: 6,
                            level: 34,
                            nature: Nature.Hasty,
                        },
                    ],
                    fieldCondition: FieldCondition.Fog,
                    x: 84,
                    y: 15.9,
                },
            ],
        },
    ],
};

export default ROUTE_210;
