import { veilstoneGym } from '@/lib/games/platinum/maps';
import { Nature } from '@/lib/static/enums';
import { Location } from '@/lib/static/types';

const VEILSTONE_GYM: Location = {
    name: 'Veilstone Gym',
    map: veilstoneGym,
    battles: [
        {
            isOptional: true,
            trainerClass: 'Black Belt',
            name: 'Colby',
            team: [
                {
                    slug: 'machoke',
                    ability: 1,
                    gender: 'male',
                    level: 23,
                    moves: ['karate-chop', 'leer', 'foresight'],
                    nature: Nature.Mild,
                    ivs: 4,
                },
                {
                    slug: 'machoke',
                    ability: 1,
                    gender: 'male',
                    level: 25,
                    moves: ['low-kick', 'foresight'],
                    nature: Nature.Gentle,
                    ivs: 4,
                },
                {
                    slug: 'machoke',
                    ability: 1,
                    gender: 'male',
                    level: 27,
                    moves: ['submission', 'leer', 'foresight'],
                    nature: Nature.Calm,
                    ivs: 4,
                },
            ],
            x: 59.8,
            y: 70,
        },
        {
            isOptional: true,
            trainerClass: 'Black Belt',
            name: 'Darren',
            team: [
                {
                    slug: 'machop',
                    ability: 1,
                    gender: 'male',
                    level: 25,
                    moves: ['karate-chop', 'foresight'],
                    nature: Nature.Gentle,
                    ivs: 4,
                },
                {
                    slug: 'meditite',
                    ability: 1,
                    gender: 'male',
                    level: 25,
                    moves: ['confusion', 'force-palm'],
                    nature: Nature.Hardy,
                    ivs: 4,
                },
                {
                    slug: 'machoke',
                    ability: 1,
                    gender: 'male',
                    level: 25,
                    moves: ['karate-chop', 'foresight'],
                    nature: Nature.Hardy,
                    ivs: 4,
                },
            ],
            x: 63.7,
            y: 42.8,
        },
        {
            trainerClass: 'Black Belt',
            name: 'Rafael',
            team: [
                {
                    slug: 'croagunk',
                    ability: 1,
                    gender: 'male',
                    level: 26,
                    moves: ['swagger', 'revenge', 'feint-attack'],
                    nature: Nature.Serious,
                    ivs: 4,
                },
                {
                    slug: 'machoke',
                    ability: 1,
                    gender: 'male',
                    level: 26,
                    moves: ['karate-chop', 'foresight'],
                    nature: Nature.Bold,
                    ivs: 4,
                },
            ],
            x: 43.8,
            y: 42.3,
        },
        {
            isOptional: true,
            trainerClass: 'Black Belt',
            name: 'Jeffery',
            team: [
                {
                    slug: 'heracross',
                    ability: 1,
                    gender: 'male',
                    level: 28,
                    moves: ['brick-break', 'aerial-ace', 'leer'],
                    nature: Nature.Mild,
                    ivs: 4,
                },
            ],
            x: 7.8,
            y: 30.4,
        },
        {
            isBoss: true,
            trainerClass: 'Leader',
            name: 'Maylene',
            team: [
                {
                    slug: 'meditite',
                    ability: 1,
                    gender: 'female',
                    level: 28,
                    moves: [
                        'drain-punch',
                        'confusion',
                        'rock-tomb',
                        'fake-out',
                    ],
                    nature: Nature.Brave,
                    ivs: 24,
                },
                {
                    slug: 'machoke',
                    ability: 1,
                    gender: 'female',
                    level: 29,
                    moves: [
                        'karate-chop',
                        'rock-tomb',
                        'strength',
                        'focus-energy',
                    ],
                    nature: Nature.Naughty,
                    ivs: 24,
                },
                {
                    slug: 'lucario',
                    ability: 1,
                    gender: 'female',
                    level: 32,
                    moves: [
                        'drain-punch',
                        'force-palm',
                        'metal-claw',
                        'bone-rush',
                    ],
                    nature: Nature.Hasty,
                    ivs: 24,
                },
            ],
            x: 48,
            y: 13,
        },
    ],
};

export default VEILSTONE_GYM;
