import fs from 'fs';
import path from 'path';
import StringHelpers from '@/lib/utils/StringHelpers';

const POKEAPI_GENERATION_URL = 'https://pokeapi.co/api/v2/generation';

type RawGeneration = {
    version_groups: { name: string }[];
};

export const sleep = (ms: number): Promise<void> =>
    new Promise((resolve) => setTimeout(resolve, ms));

export const toGenerationNumber = (generationName: string): number =>
    StringHelpers.fromRoman(generationName.replace('generation-', ''));

const fetchGenerationCount = async (): Promise<number> => {
    const response = await fetch(`${POKEAPI_GENERATION_URL}?limit=1`);
    if (!response.ok) {
        throw new Error('Failed to fetch generation count from PokeAPI.');
    }

    const body = await response.json();
    return body.count as number;
};

const fetchGeneration = async (
    generationNumber: number
): Promise<RawGeneration> => {
    const response = await fetch(
        `${POKEAPI_GENERATION_URL}/${generationNumber}`
    );
    if (!response.ok) {
        throw new Error(
            `Failed to fetch generation #${generationNumber} from PokeAPI.`
        );
    }

    return (await response.json()) as RawGeneration;
};

// Maps every version group (e.g. "diamond-pearl") to the generation number
// it belongs to, since move/ability/evolution/learnset history references a
// version group rather than a generation number directly. `delayMs` uses
// the caller's own fetch delay so this shares the same rate limit as the
// rest of that script.
export const buildVersionGroupGenerations = async (
    delayMs: number
): Promise<Map<string, number>> => {
    const generationCount = await fetchGenerationCount();
    const versionGroupGenerations = new Map<string, number>();

    for (
        let generationNumber = 1;
        generationNumber <= generationCount;
        generationNumber += 1
    ) {
        const generation = await fetchGeneration(generationNumber);
        await sleep(delayMs);

        for (const versionGroup of generation.version_groups) {
            versionGroupGenerations.set(versionGroup.name, generationNumber);
        }
    }

    return versionGroupGenerations;
};

const TYPES_FILE_PATH = path.join('src', 'lib', 'static', 'types.ts');

// Regenerates a string-literal union type of every slug in a dataset, so
// callers that reference a slug (e.g. a game's battles.ts) get compile-time
// validation and autocomplete instead of a free-form string. Called at the
// end of every pokeapi/*.ts fetch script so the type can never drift from
// the dataset it's derived from. Spliced into types.ts (between a pair of
// generated-block markers, replacing only its own block) rather than its
// own file, since "export type" is only allowed in that one file
// (.eslint-rules/code-style/no-export-type.js).
export const writeSlugType = (typeName: string, slugs: string[]): void => {
    const beginMarker = `// GENERATED-SLUGS:${typeName}:BEGIN -- regenerated by this dataset's own pokeapi/*.ts fetch script, do not edit by hand.`;
    const endMarker = `// GENERATED-SLUGS:${typeName}:END`;
    const union = [...slugs]
        .sort()
        .map((slug) => `    | '${slug}'`)
        .join('\n');
    const block = `${beginMarker}\nexport type ${typeName} =\n${union};\n${endMarker}`;

    const content = fs.readFileSync(TYPES_FILE_PATH, 'utf-8');
    const beginIndex = content.indexOf(beginMarker);
    const endIndex = content.indexOf(endMarker);

    const newContent =
        beginIndex !== -1 && endIndex !== -1
            ? content.slice(0, beginIndex) +
              block +
              content.slice(endIndex + endMarker.length)
            : `${content.trimEnd()}\n\n${block}\n`;

    fs.writeFileSync(TYPES_FILE_PATH, newContent);
};
